import '@radix-ui/themes/styles.css';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Theme } from '@radix-ui/themes';
import { ServiceCarProvider } from './context/ServiceCarContext'; // Import your data context provider here

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
   console.log("Children:", children);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <ServiceCarProvider> {/* Wrap your context provider around the children */}
            {children}
          </ServiceCarProvider>
        </Theme>
      </body>
    </html>
  );
}
